name = "google-oauth" # todo
main = "./src/index.ts"
compatibility_date = "2022-05-03"
node_compat = true

[vars]
# CLIENT_ID = "example_dev_token"
# CLIENT_SECRET = "example_dev_token"
OAUTH_CODE_CALLBACK = 'http://127.0.0.1:8719/oauth'
[env.production.vars]
OAUTH_CODE_CALLBACK = 'http://127.0.0.1:8719/oauth'
